services:

  elasticsearch:
    container_name: "elasticsearch"
    image: elasticsearch:7.14.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          memory: 1024M

  redis:
    container_name: "redis"
    image: redis:6.2.5
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 1024M


